# Generated by Django 4.0.4 on 2022-04-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario_alter_evento_datacriacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='sub_titulo',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
